### ISSUE TITLE
Set up Jenkins for deployment to aws cloudfront. 

### ISSUE THREAD

**Issue by abrahamq** [urbanriskmap/cognicity-rem-analysis#1]

**Comment by matthewberryman** [comment]
Have done this (got build.dev of master going to https://rem-analysis.petabencana.id ) - just waiting for a few cloudfront things to settle first before I can finish testing and close it off, I may need to use the redirection hack as per https://github.com/urbanriskmap/petabencana.id/issues/71 too. I haven't used build.prod as that's broken for me. Let me know if you want your other branch deployed.

**Comment by matthewberryman** [comment]
CloudFront is finished its stuff and I have tested and seems Ok, but re-open if any issues @abrahamq
