### ISSUE TITLE
leaflet is butchering the lng attribute on markers somehow

### ISSUE THREAD

**Issue by abrahamq** [urbanriskmap/cognicity-rem-analysis#6]
for report with pkey=4 from production: the db says it is at: 

cognicity> SELECT st_asgeojson(the_geom) FROM cognicity.all_reports WHERE pkey=4;
+-----------------------------------------------------+
| st_asgeojson                                        |
|-----------------------------------------------------|
| {"type":"Point","coordinates":[106.931374,-6.1129]} |
+-----------------------------------------------------+

but leaflet believes it to be at lng: 106.9311323.... and there's a whole lot of points also on this lng. 

Somewhere along the line we're mangling the lng attribute, maybe when we convert from topojson to geojson?

**Comment by matthewberryman** [comment]
I've tested both topojson:
```
                    {
                        "type": "Point",
                        "properties": {
                            "pkey": "4",
                            "created_at": "2017-01-13T06:11:00.000Z",
                            "source": "qlue",
                            "status": "confirmed",
                            "url": null,
                            "image_url": "https://lh3.googleusercontent.com/z-ata9Zdvhe_gWQmqktI2oY45kPbysNrlLVmX7ZXiM_6muRVfXT3g2ci5lhJ4optCRdsNIhX2_DXiD4KmNcTKznG8Oc=s480-c",
                            "disaster_type": "flood",
                            "report_data": null,
                            "tags": {
                                "instance_region_code": "jbd",
                                "local_area_id": "2338"
                            },
                            "title": " ",
                            "text": "#drainaseburuk, @ marsanregu3 klu tl sllu abal-abal, kmrn apa yg dikerjain lumpurnya msh sprti laporan sblmnya."
                        },
                        "coordinates": [
                            106.931374,
                            -6.1129
                        ]
                    },

```

 and geojson:
```
            {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                        106.931374,
                        -6.1129
                    ]
                },
                "properties": {
                    "pkey": "4",
                    "created_at": "2017-01-13T06:11:00.000Z",
                    "source": "qlue",
                    "status": "confirmed",
                    "url": null,
                    "image_url": "https://lh3.googleusercontent.com/z-ata9Zdvhe_gWQmqktI2oY45kPbysNrlLVmX7ZXiM_6muRVfXT3g2ci5lhJ4optCRdsNIhX2_DXiD4KmNcTKznG8Oc=s480-c",
                    "disaster_type": "flood",
                    "report_data": null,
                    "tags": {
                        "instance_region_code": "jbd",
                        "local_area_id": "2338"
                    },
                    "title": " ",
                    "text": "#drainaseburuk, @ marsanregu3 klu tl sllu abal-abal, kmrn apa yg dikerjain lumpurnya msh sprti laporan sblmnya."
                }
            },
```
and as you can see I get the same co-ordinates, the same as you get from the postgresql query.
Where in leaflet are you seeing the wrong co-ordinate? Let me know (and also fix https://github.com/urbanriskmap/cognicity-rem-analysis/issues/7 ) and I can test that.

**Comment by tomasholderness** [comment]
Hi @matthewberryman - this was due to a bug in DBGeo which wasn't passing the correct quantization parameter in the topojson library for conversion from geojson to topojson. This was a tricky bug, quantization only really starts to become noticeable with large numbers of points (as would be seen with analytics, but not the live service (too few reports on the map at one time)). Hence, why you couldn't recreate above.

@abrahamq requested a new version of the library be published to NPM and this has been done! (https://github.com/jczaplew/dbgeo/issues/7)

Going to leave this open as think there is still some tidying @abrahamq wants to do.

Thanks for input on these issues - really useful.

**Comment by matthewberryman** [comment]
@talltom The above extracts were from a request for a whole monsoon's worth of data- not sure why I couldn't reproduce, then, perhaps I picked up the new version of the library.
